apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekstest
  region: ap-northeast-2

nodeGroups:
  - name: ng-1-workers
    labels: {role: worker}
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    iam: 
      withAddonPolicies:
          awsLoadBalancerController: true
          externalDNS: true

